language: node_js
node_js:
- '5'
- '4'
script: gulp test
install:
- npm install -g firebase-tools
- npm install
after_success:
- firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
