language: node_js
node_js:
- '5'
- '4'
before_script:
- npm install -g gulp
script: gulp test
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
