language: node_js
node_js:
- '5'
- '4'
before_script:
- npm install -g gulp
script: gulp test
deploy:
  provider: azure_web_apps
  username: azure_deployment_user
  password: azure_deployment_password
  site: azure_deployment_sitename
